<?php

return [
    'languages' =>  ["Arabic", "Bengali", "Dutch", "English", "French", "German", "Hindi", "Indonesian", "Italian", "Japanese", "Korean", "Malay", "Mandarin Chinese", "Marathi", "Persian (Farsi)", "Polish", "Portuguese", "Punjabi", "Russian", "Spanish", "Swahili", "Tamil", "Telugu", "Thai", "Turkish", "Tagalog (Filipino)", "Ukrainian", "Urdu", "Vietnamese", "Yoruba"],
    'positions' => ["CEO", "CTO", "CFO", "COO", "HR Manager", "Software Engineer", "Product Manager", "Marketing Director", "Sales Manager", "Customer Support Representative", "Data Scientist", "Graphic Designer", "Operations Analyst", "Business Analyst", "Quality Assurance Specialist", "IT Administrator", "Network Engineer", "Legal Counsel", "Event Coordinator", "Public Relations Specialist", "Content Writer", "Research Scientist", "Logistics Coordinator", "Supply Chain Manager", "Project Manager", "Architect", "Electrical Engineer", "Mechanical Engineer", "Civil Engineer", "Chemical Engineer", "Executive Assistant", "Social Media Manager", "UI/UX Designer", "Systems Administrator", "Database Administrator", "Financial Analyst", "Investment Analyst", "Health and Safety Officer", "Warehouse Manager", "Recruitment Specialist", "Training Coordinator", "Legal Secretary", "Business Development Manager", "Facilities Manager", "IT Support Specialist", "Customer Success Manager", "Environmental Scientist", "Technical Writer", "Mobile App Developer"],
    'industry_types' => [
        "Information Technology",
        "Healthcare",
        "Finance",
        "Manufacturing",
        "Retail",
        "Education",
        "Hospitality",
        "Agriculture",
        "Entertainment",
        "Transportation",
        "Automotive",
        "Construction",
        "Telecommunications",
        "Energy",
        "Pharmaceuticals",
        "Media",
        "Real Estate",
        "Insurance",
        "Consulting",
        "Aerospace",
        "Government",
        "Non-profit",
        "Food and Beverage",
        "E-commerce",
        "Gaming",
        "Environmental",
        "Biotechnology",
        "Sports",
        "Fashion",
        "Travel",
        "Advertising",
        "Architecture",
        "Legal",
        "Art",
        "Music",
        "Film",
        "Design",
        "Publishing",
        "Software",
        "Hardware",
        "Consumer Electronics",
        "Oil and Gas",
        "Mining",
        "Renewable Energy",
        "Chemical",
        "Logistics",
        "Shipping",
        "Pharmaceutical",
        "Health and Fitness",
        "Education Technology",
        "Marketing",
        "Human Resources",
        "Social Media",
        "Market Research",
        "Tourism",
        "Aviation",
        "Textile",
        "Automobile",
        "Biomedical",
        "Cosmetics",
        "Culinary",
        "Event Management",
        "Fashion Design",
        "Furniture",
        "Home Improvement",
        "Information Security",
        "Interior Design",
        "Investment Banking",
        "Jewelry",
        "Legal Services",
        "Management Consulting",
        "Medical Devices",
        "Nanotechnology",
        "Petroleum",
        "Public Relations",
        "Renewable Resources",
        "Robotics",
        "Social Networking",
        "Wine and Spirits",
        "Zoology",
    ],
    'country' => [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo (Congo-Brazzaville)",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czechia (Czech Republic)",
        "Democratic Republic of the Congo (Congo-Kinshasa)",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Holy See (Vatican City)",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar (Burma)",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Macedonia",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine State",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Korea",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Syria",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States of America",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe",
    ],
    $companyTypes = [
        "Sole Proprietorship",
        "Partnership",
        "Limited Liability Company",
        "Corporation",
        "Cooperative",
        "Nonprofit Organization",
        "Franchise",
        "Limited Partnership",
        "Joint Venture",
        "Professional Corporation"
    ]
];

