name: CI_CD Laravel
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create SSH Directory
      run: mkdir -p ~/.ssh/

    - name: Add SSH Private Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
          
    - name: Deploy to Server
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 522 appdev1@app.asiadealhub.com '
          cd /home/apps/application/app
          git pull origin master
        '
